server:
  port: 8092
spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
      - id: customer-service
        uri: http://localhost:8086/
        predicates:
        - Path=/customers/**
          
      - id: product-service
        uri: http://localhost:8089/
        predicates:
        - Path=/products/**
          
